repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Verze repozitáře pre-commit-hooks
    hooks:
      - id: trailing-whitespace       # Odstraní koncové mezery na řádcích
      - id: end-of-file-fixer         # Ujistí se, že soubory končí prázdným řádkem
      - id: check-yaml                # Kontrola syntaktické správnosti YAML souborů
      - id: check-added-large-files   # Upozorní na přidání velkých souborů (např. nad 5MB)
      - id: check-merge-conflict      # Upozorní na pozůstatky merge konfliktů
      - id: check-ast
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - "--max-line-length=120"  # Maximální délka řádku nastavena na 100 znaků
        files: "\\.(py)$"  # Použije kontrolu na všechny Python soubory
  - repo: local
    hooks:
      - id: mypy
        name: "Check Typing Annotations with mypy"
        entry: mypy
        language: system
        types: [python]
        args:
          - --disallow-untyped-defs  # Zakáže definice funkcí bez typových anotací
          - --disallow-incomplete-defs  # Zakáže částečné typové anotace
        files: "\\.(py)$"  # Použije kontrolu na všechny Python soubory
  - repo: local
    hooks:
      - id: coverage-check
        name: "Run Tests with Coverage"
        entry: bash -c "cd $(git rev-parse --show-toplevel) && coverage run -m unittest discover -s tests -p 'test_*.py' -v 2>&1"
        language: system
        types: [python]
    repos:
      - repo: https://github.com/pre-commit/mirrors-prettier
        rev: v3.0.0
        hooks:
          - id: prettier
            args: ["--check", "--write"]
            files: "\\.(html|css|scss)$"
